repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.4
  hooks:
    # Run ruff with isort formatter
    - id: ruff
      types_or: [ python, pyi ]
      args: [ "--select", "I", "--fix" ]
    # Run ruff
    - id: ruff
      types_or: [ python, pyi ]
      args: [ "--fix" ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]