name: Pre-commit
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master

jobs:
  pre-commit-check:
    name: Check pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Pre-commit
        run: pip install pre-commit
      - run: pre-commit run --all-files