path: /workspace/Global/dataset
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Keypoints
kpt_shape: [4, 2]  # [number of keypoints, number of dim]
flip_idx: [0, 1, 2, 3]

# Classes
names:
  0: weapon

