path: /workspace/Global/datasetClassif
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Keypoints
kpt_shape: [4, 2]  # [number of keypoints, number of dim]
flip_idx: [0, 1, 2, 3]

# Classes
names:
  0: Semi_auto style chasse
  1 : Pompe
  2 : Levier_sous_garde
  3 : Semi_auto militaire autre
  4 : Semi_auto militaire milieu 20eme
  5 : Epaule à un coup
  6 : Epaule à verrou

